import { FormEvent, useEffect, useState } from 'react';
import ReactECharts from 'echarts-for-react';
import { QRCodeSVG } from 'qrcode.react';
import { API, request } from './api';
import type { Campaign, FunnelItem, Participant, Stage } from './types';
import './admin.css';

export function AdminApp(){const [ready,setReady]=useState<boolean>();useEffect(()=>{request('/api/auth/me').then(()=>setReady(true)).catch(()=>setReady(false));},[]);if(ready===undefined)return <div className="admin-loading">正在载入管理后台…</div>;return ready?<Dashboard onLogout={()=>setReady(false)}/>:<Login onLogin={()=>setReady(true)}/>}
function Login({onLogin}:{onLogin:()=>void}){const [error,setError]=useState('');const [busy,setBusy]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await request('/api/auth/login',{method:'POST',body:JSON.stringify({username:f.get('username'),password:f.get('password')})});onLogin();}catch(e){setError((e as Error).message)}finally{setBusy(false)}}return <main className="login-shell"><form className="login-card" onSubmit={submit}><span className="brand-mark">R</span><h1>管理后台</h1><p>查看训练营每一步真实转化</p><label>用户名<input name="username" defaultValue="admin" required/></label><label>密码<input name="password" type="password" required/></label>{error&&<div className="alert error">{error}</div>}<button disabled={busy}>{busy?'登录中…':'登录'}</button></form></main>}
function Dashboard({onLogout}:{onLogout:()=>void}){const [campaigns,setCampaigns]=useState<Campaign[]>([]);const [selected,setSelected]=useState('');const [stages,setStages]=useState<Stage[]>([]);const [analytics,setAnalytics]=useState<{funnel:FunnelItem[];overallRate:number}>({funnel:[],overallRate:0});const [people,setPeople]=useState<Participant[]>([]);const [view,setView]=useState<'overview'|'links'|'people'|'settings'>('overview');const [modal,setModal]=useState<'campaign'|'stage'|null>(null);const [error,setError]=useState('');
const campaign=campaigns.find(c=>c.id===selected);async function loadCampaigns(){const c=await request<Campaign[]>('/api/campaigns');setCampaigns(c);if(!selected&&c[0])setSelected(c[0].id)}async function loadDetail(){if(!selected)return;try{const [s,a,p]=await Promise.all([request<Stage[]>(`/api/campaigns/${selected}/stages`),request<any>(`/api/campaigns/${selected}/analytics`),request<Participant[]>(`/api/campaigns/${selected}/participants`)]);setStages(s);setAnalytics(a);setPeople(p)}catch(e){setError((e as Error).message)}}useEffect(()=>{loadCampaigns().catch(e=>setError(e.message))},[]);useEffect(()=>{loadDetail()},[selected]);
async function logout(){await request('/api/auth/logout',{method:'POST'});onLogout()}async function updateStatus(status:Campaign['status']){if(!campaign)return;await request(`/api/campaigns/${campaign.id}`,{method:'PATCH',body:JSON.stringify({status})});await loadCampaigns();}
const nav=[['overview','数据概览'],['links','签到入口'],['people','参与者'],['settings','活动设置']] as const;return <div className="admin-layout"><aside><div className="admin-brand"><span className="brand-mark">R</span><div><b>留存雷达</b><small>运营数据中心</small></div></div><nav>{nav.map(([key,label])=><button className={view===key?'active':''} onClick={()=>setView(key)} key={key}>{label}</button>)}</nav><button className="logout" onClick={logout}>退出登录</button></aside><section className="admin-main"><header><div><span className="eyebrow">DEVELOPER RETENTION RADAR</span><h1>{campaign?.name??'创建第一个训练营'}</h1></div><div className="header-actions"><select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">选择活动</option>{campaigns.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><button onClick={()=>setModal('campaign')}>新建活动</button></div></header>{error&&<div className="alert error">{error}</div>}{!campaign?<Empty title="还没有训练营" text="创建活动后即可生成任务入口并追踪转化。" action={()=>setModal('campaign')}/>:view==='overview'?<Overview data={analytics} participants={people.length}/>:view==='links'?<Links stages={stages}/>:view==='people'?<People people={people} campaignId={campaign.id}/>:<Settings campaign={campaign} stages={stages} onStatus={updateStatus} onAddStage={()=>setModal('stage')}/>}</section>{modal==='campaign'&&<CampaignModal close={()=>setModal(null)} done={async()=>{setModal(null);await loadCampaigns()}}/>}{modal==='stage'&&campaign&&<StageModal campaign={campaign} position={stages.length+1} close={()=>setModal(null)} done={async()=>{setModal(null);await loadDetail()}}/>}</div>}
function Overview({data,participants}:{data:{funnel:FunnelItem[];overallRate:number};participants:number}){const max=data.funnel[0]?.count??0;const option={tooltip:{trigger:'item'},series:[{type:'funnel',left:'8%',top:20,bottom:20,width:'84%',min:0,max:max||1,minSize:'28%',maxSize:'100%',sort:'descending',gap:3,label:{show:true,position:'inside',formatter:'{b}  {c} 人',fontSize:14,color:'#fff'},itemStyle:{borderColor:'#fff',borderWidth:2},data:data.funnel.map(x=>({name:x.name,value:x.count}))}]};return <><div className="metrics"><Metric label="报名人数" value={data.funnel[0]?.count??participants} suffix="人"/><Metric label="最终完成人数" value={data.funnel.at(-1)?.count??0} suffix="人"/><Metric label="整体完成率" value={data.overallRate} suffix="%"/><Metric label="任务阶段" value={data.funnel.length} suffix="个"/></div><div className="content-grid"><article className="panel chart-panel"><div className="panel-title"><div><h2>实时转化漏斗</h2><p>数据随每一次签到自动更新</p></div></div>{data.funnel.length?<ReactECharts option={option} style={{height:360}}/>:<Empty title="等待第一笔数据" text="创建并开放签到入口后，漏斗将在这里出现。"/>}</article><article className="panel"><div className="panel-title"><div><h2>阶段转化</h2><p>定位流失最明显的任务节点</p></div></div><div className="stage-list">{data.funnel.map((x,i)=><div className="stage-row" key={x.id}><span>{i+1}</span><div><b>{x.name}</b><small>{i===0?'基准阶段':`较上一阶段 ${x.conversionRate}%`}</small></div><strong>{x.count}</strong></div>)}</div></article></div></>}
function Metric({label,value,suffix}:{label:string;value:number;suffix:string}){return <article className="metric"><span>{label}</span><strong>{value}<small>{suffix}</small></strong></article>}
function Links({stages}:{stages:Stage[]}){const base=location.origin;return <div className="panel"><div className="panel-title"><div><h2>统一签到入口</h2><p>下载或投屏二维码，参与者无需注册账号</p></div></div><div className="qr-grid">{stages.map(s=>{const url=`${base}/checkin/${s.id}`;return <article className="qr-card" key={s.id}><QRCodeSVG value={url} size={132} level="M"/><div><span>阶段 {s.position}</span><h3>{s.name}</h3><p>{s.description||'扫码完成本阶段任务签到'}</p><button className="secondary" onClick={()=>navigator.clipboard.writeText(url)}>复制链接</button></div></article>})}</div>{!stages.length&&<Empty title="暂无签到阶段" text="前往活动设置添加阶段。"/>}</div>}
function People({people,campaignId}:{people:Participant[];campaignId:string}){return <div className="panel"><div className="panel-title"><div><h2>参与者名单</h2><p>共 {people.length} 名已报名参与者</p></div><a className="secondary button-link" href={`${API}/api/campaigns/${campaignId}/export.csv`}>导出 CSV</a></div><div className="table-wrap"><table><thead><tr><th>姓名</th><th>学号</th><th>手机号</th><th>学校</th><th>完成阶段</th></tr></thead><tbody>{people.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{p.student_id}</td><td>{p.phone}</td><td>{p.school||'—'}</td><td>{p.checkins.length}</td></tr>)}</tbody></table></div>{!people.length&&<Empty title="还没有参与者" text="报名入口收到数据后会自动出现在这里。"/>}</div>}
function Settings({campaign,stages,onStatus,onAddStage}:{campaign:Campaign;stages:Stage[];onStatus:(s:Campaign['status'])=>void;onAddStage:()=>void}){return <div className="content-grid settings"><article className="panel"><h2>活动状态</h2><p className="muted">只有“进行中”的活动允许公开签到。</p><div className="status-actions">{(['draft','active','closed'] as const).map(s=><button className={campaign.status===s?'':'secondary'} onClick={()=>onStatus(s)} key={s}>{{draft:'草稿',active:'进行中',closed:'已结束'}[s]}</button>)}</div></article><article className="panel"><div className="panel-title"><div><h2>任务阶段</h2><p>阶段删除后历史签到仍然保留</p></div><button onClick={onAddStage}>添加阶段</button></div><div className="stage-list">{stages.map(s=><div className="stage-row" key={s.id}><span>{s.position}</span><div><b>{s.name}</b><small>{s.kind}</small></div></div>)}</div></article></div>}
function CampaignModal({close,done}:{close:()=>void;done:()=>void}){return <Modal title="新建训练营" close={close}><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);const c=await request<Campaign>('/api/campaigns',{method:'POST',body:JSON.stringify({name:f.get('name'),description:f.get('description'),status:'draft'})});const defaults=[['活动报名','填写信息加入训练营','registration'],['账号开通','确认华为云账号已开通','checkin'],['完成首个任务','完成并签到第一个实战任务','checkin'],['最终提交','提交最终作品链接','submission']];for(let i=0;i<defaults.length;i++)await request(`/api/campaigns/${c.id}/stages`,{method:'POST',body:JSON.stringify({name:defaults[i][0],description:defaults[i][1],kind:defaults[i][2],position:i+1})});done()}}><label>活动名称<input name="name" required minLength={2} placeholder="如：华为云数据库实战营"/></label><label>活动说明<textarea name="description" rows={3} placeholder="活动目标与面向人群"/></label><button>创建并生成默认阶段</button></form></Modal>}
function StageModal({campaign,position,close,done}:{campaign:Campaign;position:number;close:()=>void;done:()=>void}){return <Modal title="添加任务阶段" close={close}><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await request(`/api/campaigns/${campaign.id}/stages`,{method:'POST',body:JSON.stringify({name:f.get('name'),description:f.get('description'),kind:f.get('kind'),position})});done()}}><label>阶段名称<input name="name" required/></label><label>阶段说明<textarea name="description" rows={3}/></label><label>阶段类型<select name="kind"><option value="checkin">普通签到</option><option value="submission">作品提交</option><option value="registration">报名</option></select></label><button>添加阶段</button></form></Modal>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><div className="panel-title"><h2>{title}</h2><button className="icon-button" onClick={close}>×</button></div>{children}</div></div>}
function Empty({title,text,action}:{title:string;text:string;action?:()=>void}){return <div className="empty"><b>{title}</b><p>{text}</p>{action&&<button onClick={action}>立即创建</button>}</div>}
